---
- name: Install Httpd...
  hosts: all
  become: true
  tasks:
  - name: Installing httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start apache
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: install apache2
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"

  - name: start apache2
    service:
      name: apache2
      enabled: yes
      state: reloaded
    when: ansible_os_family == "Debian"
    
  - name: copy index.html
    copy:
      src: /etc/ansible/index.html
      dest: /var/www/html/index.html
      mode: 0666
      

